### PR TITLE
Added methods to TraceInfo to register callbacks with IARGLIST.

### PR DESCRIPTION
**Pull request by ElliotLockerman**
I added two new methods, `insertCallList()` and `insertSwitchCallList()`, which behave like `insertCall()` and `insertSwitchCall()`, respectively, but take an `IARGLIST` instead of loose `IARGS`.

These are necessary because an `IARGLIST` must be freed after it is used; normally, this would be done by the tool immediately after registering the callback, but with libspin, the list must live longer than the call to `insertCall()`/`insertSwitchCall`

### CODE REVIEW

**Comment by VictorYing** [comment]
Hi @ElliotLockerman and @neonachronism , thanks for opening this PR. I was excited to hear libspin was useful for Livia, and I look forward to seeing more of your work.

This commit makes sense to me and looks pretty harmless. It's a bit unfortunate that we don't have any tests for libspin other than our respective simulators. Since this is our first time receiving a PR, I'll check with some of my collaborators on how we want to handle this.

**Comment by VictorYing** [comment]
Hey @ElliotLockerman, is your group still actively building and using simulators based on libspin?
If so, would you be interested in sharing responsibility in maintaining libspin as a CMU-MIT collaboration going forward?

**Comment by ElliotLockerman** [comment]
Thanks for accepting the PR. 
We don't have that much experience with libspin internals - what did you have in mind?

**Comment by VictorYing** [comment]
I don't expect that libspin will need to change very much, but I'm thinking we might want to set up a shared Slack channel where known libspin users can chat about any issues/changes, and we can try to live together at a shared HEAD where we have a greater chance of benefiting from each other's ideas. I could also create PRs for changes from our end and give you (and anybody else who is interested) some time to review/test them.

**Comment by VictorYing** [comment]
At this point, I think libspin's internal design is unlikely to see a lot of change, and future changes may be about adding/improving compatibility with more system configurations (future OS versions?) and making the build system more flexible.

**Comment by ElliotLockerman** [comment]
Ok, that sounds good.

**Comment by VictorYing** [comment]
I invited elockerm@cs.cmu.edu as a guest to the #libspin channel of the Sanchez group's Slack workspace (csail-architorture.slack.com) Please let me know if you have difficulty signing in.

**Comment by ElliotLockerman** [comment]
Thank you, I joined.

**Pull request merged**
